// This code is auto generated by Excel VBA. Do NOT edit it manually !
// Copyright (C) 2016 Nanjing Xiaoxi Network Technology Co., Ltd. (http://www.xiaoxigame.com/)

using XPlugin.Localization;

public static partial class LString
{
	/// <summary>
	/// 加载UIString
	/// </summary>
	public static void Load_UIString()
	{
		LocalizedDict.Load("UIString");
	}
	
	/// <summary>
	/// 设置
	/// </summary>
	public const string UI_SETTING = "UI_SETTING";
	
	/// <summary>
	/// 确定
	/// </summary>
	public const string UI_OK = "UI_OK";
	
	/// <summary>
	/// 第{0}关，第{1}章
	/// </summary>
	public const string UI_FORMAT = "UI_FORMAT";
	
	/// <summary>
	/// 这是<para/>很多行<para/>很多行<para/>。。。
	/// </summary>
	public const string UI_MULTI_LINE = "UI_MULTI_LINE";
	
	/// <summary>
	/// 确定_3
	/// </summary>
	public const string UI_OK_3 = "UI_OK_3";
	
	/// <summary>
	/// 确定_4
	/// </summary>
	public const string UI_OK_4 = "UI_OK_4";
	
	/// <summary>
	/// 联网
	/// </summary>
	public const string UI_Button_Online = "UI_Button_Online";
	
	/// <summary>
	/// 单机
	/// </summary>
	public const string UI_Button_Localization = "UI_Button_Localization";
}
